### PR TITLE
change dummy_hcd:MAX_NUM_UDC from 2 to 4

### PR DESCRIPTION
**Pull request by vaishnav98**
The project clickboard support through greybus(https://github.com/vaishnav98/gbsim/wiki/Beagleboard-GSoC-'19:--Clickboard-Support-Under-Greybus) uses dummy_hcd emulated UDC for running the greybus simulator and requires an instance of emulated UDC for each mikrobus port, since the Beaglebone Black Mikrobus Cape has 4 Mikrobus Slots for serving all of the ports through greybus simulator at a time requires 4 emulated dummy_hcd UDC.

Also it would be really helpful if USB_DUMMY_HCD was enabled(as module) in future beagleboard linux builds so that the installation process for Greybus Simulator becomes simpler

### CODE REVIEW

**Comment by RobertCNelson** [comment]
thanks @vaishnav98 , i'll merge this..  PS do you want me to start back-porting greybus from mainline, that way we are only really working on one greybus tree?

Yeap, i'll ad usb_dummy_hcd 

Regards,

**Comment by vaishnav98** [comment]
thank you @RobertCNelson , It would be great if you could perform back-porting greybus from mainline as we are planning to work on some modifications to the greybus manifests to support platform data and other additions to greybus.

**Comment by jadonk** [comment]
Do we have greybus on 4.14 now or does it require something newer?

**Comment by RobertCNelson** [comment]
Opps, this got merged, but didn't close.. I backported GreyBus in our v4.14.x branch from v4.19.81, beyond that was issues..

**Pull request closed without merging**
