### PR TITLE
4.1 abbbi rc1

### PR DESCRIPTION
**Pull request by ohporter**
This series supports the Arrow BeagleBone Black Industrial compatible board. It adds support for a componentized drm adv7511 driver with audio support from the vendor (modified from upstream version). Ultimately, these changes should be integrated with the adv7511.c driver upstream. It also backports the upstream componentized support for tilcdc. am335x-abbbi.dts is added and am335x-boneblack.dts is converted to use the newer DT graph bindings to match external encoders with drm drivers like tilcdc.

This is tested on both BBB Rev. A5A and the ABBI Rev. A0 board. The kernel images/modules are identical and the hdmi encoder matched to the tilcdc driver is selected by the loaded DTB (either tda998x or adihdmi).

A U-Boot change is required in order to identify the ABBBI board and load the correct .dtb. I've pushed this support (just a two line change on top of the last beagleboard.org U-Boot release patch I found) to https://github.com/konsulko/u-boot/tree/v2015-10-abbbi. I don't see a bb.org U-Boot tree to which I could send a  pull request for that change.

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks @ohporter !

btw, is this board "available"?  I'd like to pick one up, so i don't break anything. ;)

All merged up for "r29" nett week. (kernel is frozen for sunday's weekly snapshot image), so it'll get pushed out at the latest by thursday..

Regards,

**Comment by RobertCNelson** [comment]
@ohporter can you do me a favor:

please run:

```
wget https://raw.githubusercontent.com/RobertCNelson/boot-scripts/master/device/bone/tester/show-eeprom.sh
sudo /bin/bash show-eeprom.sh
```
and i can add it our bb.org eeprom database..

Regards,

**Comment by ohporter** [comment]
@RobertCNelson wow, that was quick! Thanks for picking this up. I will talk to the ODM and explain to them that they need to send you one so it can be maintained. Will sync with you offline about that.

Here's the eeprom info:

# /bin/bash show-eeprom.sh
eeprom: [�U3�A335BNLTAIA0]
eeprom raw: [00000000  aa 55 33 ee 41 33 33 35  42 4e 4c 54 41 49 41 30  |.U3.A335BNLTAIA0|]

**Comment by RobertCNelson** [comment]
Thanks @ohporter just added that to the eeprom list, we need to keep these guys from stepping on each other. ;)

https://github.com/beagleboard/image-builder/blob/master/readme.md

Regards,

**Comment by pdp7** [comment]
@ohporter I don't see am335x-abbbi.dts in mainline.  Is there a reason that you did not submit it?

**Pull request closed without merging**
