### PR TITLE
Change USB class for RNDIS

### PR DESCRIPTION
**Pull request by dlech**
This is a hack to change the USB class/subclass/protocol for the RNDIS
USB gadget function. According to [this][1], this is "RNDIS over Ethernet".
This configuration is recognized by rndiscmp.inf in Windows so that the
correct driver loads without the need for a custom signed .inf.
Furthermore, it is ignored on macOS and Linux (so we can use CDC/ECM
instead).

[1]: http://www.usb.org/developers/defined_class/#BaseClassEFh

### CODE REVIEW

**Comment by dlech** [comment]
This goes along with <https://github.com/RobertCNelson/boot-scripts/pull/51>.

**Comment by RobertCNelson** [comment]
Thanks! tagged as r90

**Comment by jadonk** [comment]
Sweet! Even as-is, this should eliminate driver install on Windows Vista and newer.

**Comment by RobertCNelson** [comment]
@dlech thanks for the ping, i'll watch out for that, especially as our next lts (v4.14.x) is coming up.

**Pull request closed without merging**
