### PR TITLE
Add device tree file for the Modio BB cape

### PR DESCRIPTION
**Pull request by Spindel**
The Modio cape exposes 4 UARTs as 3xRS485 and 1xRS232 port on the
BeagleBoneBlack.

To function, it needs the cape manager to be disabled, since the capemanager
shares pins with one of the UART devices.

This device tree file is based on the minimal dts file. It currently sets up
RTS pins as GPIO pins, which the OMAP_SERIAL driver can function with.

So far, I have not managed to make the driver simply set the RTS flag in order
to control the port.

Signed-off-by: D.S. Ljungmark <ljungmark@modio.se>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
thanks @Spindel ! sorry for the delay, this will be pushed out as part of "r72'

**Comment by Spindel** [comment]
Thank you!

**Comment by Spindel** [comment]
Ping?

**Comment by RobertCNelson** [comment]
@Spindel pong

So did you try r72 or later?

Regards

**Comment by Spindel** [comment]
Cheers, feel free to close.

**Pull request closed without merging**
