### PR TITLE
Fix remoteproc to work with the PRU GNU Binutils port

### PR DESCRIPTION
**Pull request by dinuxbg**
PRU IRAM addresses need to be masked before being handled to
remoteproc. This is due to PRU Binutils' lack of separate address
spaces for IRAM and DRAM.

Signed-off-by: Dimitar Dimitrov <dinuxbg@gmail.com>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
@dinuxbg , crap i just pushed a rebuild today.. it'll take a little bit to refresh this out..

PS, now the PRU is mainline on gcc, what do we need with your packages to have everything up to date.. I'd like to have this done by April 6th (the day before):

https://elinux.org/Beagleboard:Latest-images-testing#List_of_releases

Regards,

**Comment by RobertCNelson** [comment]
@dinuxbg added to tracker: https://github.com/beagleboard/Latest-Images/issues/16

**Comment by dinuxbg** [comment]
> PS, now the PRU is mainline on gcc, what do we need with your packages to have everything up to date.. I'd like to have this done by April 6th (the day before):

The entire toolchain is now merged in mainline (Binutils, GCC, newlib). Only [the per-SoC linker](https://github.com/dinuxbg/gnuprumcu) scripts are a separate project, akin to AVR and MSP430 toolchains. I still maintain debian packaging and small improvements not yet mainlined in https://github.com/dinuxbg/gnupru .

I'll try to update the packaging scripts in https://github.com/dinuxbg/repos . I'm not sure what I'm doing wrong, but it always takes me a lot of time, hence the rare updates :)

**Comment by jadonk** [comment]
Does this pull request still need to be open or is everything merged? Do we need an upstream patch?

**Comment by dinuxbg** [comment]
4.19.94-ti-r43 has the fix, so I'm closing the request. Once pru remoteproc is merged in real mainline I'll also send the fix to linux-omap.

**Pull request closed without merging**
