### PR TITLE
Add am3352_som_defconfig

### PR DESCRIPTION
**Pull request by vinifr**
Add am3352_som_defconfig file for am3352-som-evb board.

Signed-off-by: Dimitar Gamishev <hehopmajieh@debian.bg>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Hi @vinifr, we like everyone to use the same base "config" please re-test with "bb.org_defconfig" and ping me what configs you guys need enabled...  (random special configs tend to end up ignored/broken over time..)

Here's the current "am3352_som_defconfig" vs "bb.org_defconfig" delta...

https://gist.github.com/RobertCNelson/34f1977514c055e0a3a2

**Comment by vinifr** [comment]
It's ok. I will analyze.

**Comment by vinifr** [comment]
Hi Robert,

After analyzing a lot of options, I think a few configs must be enabled:

+CONFIG_SERIAL_OMAP=y (OK)
+CONFIG_SERIAL_OMAP_CONSOLE=y (OK)
+CONFIG_USB_MUSB_AM35X=m (OK)
+CONFIG_USB_MUSB_OMAP2PLUS=m (OK)
+CONFIG_TWL6030_USB=m (OK)
+CONFIG_TOUCHSCREEN_PIXCIR=m (OK)

However, even after I enable SERIAL_OMAP_CONSOLE option, the console via UART does not work. The rest seems to be ok.

**Comment by vinifr** [comment]
Ok, nevermind.

I changed console=ttyO0 to console=ttyS0 and it worked.

**Comment by vinifr** [comment]
Now I get continuous log messages as follows:

[  213.871664] cpu cpu0: clk_voltdm_notifier_handler: Failed to scale voltage(1100000): -22
[  213.879882] cpu cpu0: clk_voltdm_notifier_handler: Failed to scale voltage(950000): -22
[  213.894166] cpu cpu0: failed to set clock rate: -16
[  213.899136] cpufreq: __target_index: Failed to change cpu frequency: -16

**Comment by RobertCNelson** [comment]
So voltdm assumes we can change the regulators, let's disable that for the olimex board..

I'm thinking the quickest hack for v4.1. would be to:

add: (might need a of_machine* header file)
```
if (!of_machine_is_compatible("ti,am335x-olimex-som"))
```
https://github.com/beagleboard/linux/blob/4.1/arch/arm/mach-omap2/opp33xx_data.c#L84

and

```
compatible = "ti,am335x-olimex-som", "ti,am33xx";
```
https://github.com/beagleboard/linux/blob/4.1/arch/arm/boot/dts/am335x-olimex-som.dts#L15

**Comment by RobertCNelson** [comment]
btw, with serial, we do have "CONFIG_SERIAL_8250_OMAP_TTYO_FIXUP=y" enabled..

So u-boot can still set "ttyOx" and the kernel will change it to "ttySx" automatically, while systemd knows what do with 'console=xyz' set in the bootargs to launch getty. udev needs this rule to help:

https://github.com/rcn-ee/repos/blob/master/bb-bb-customizations/suite/jessie/debian/60-omap-tty.rules

So atleast for systemd/udev based systems the console name change shouldn't be a big issue. ;)

**Comment by RobertCNelson** [comment]
Please test:

https://gist.github.com/RobertCNelson/719b7f8af1c6c4b45e25

on top of 4.1

**Comment by vinifr** [comment]
hi,
I tested original bb.org_defconfig plus your patch and it worked perfectly! Thanks Robert. :D

**Comment by vinifr** [comment]
There is another error, but I think is irrelevant: http://pastebin.com/tYkagibk

**Comment by RobertCNelson** [comment]
So am335x-pru0-fw/am335x-pru1-fw are free for the end user to implement anything they want.  The kernel's just complaining that it couldn't find your custom firmware. ;)

**Pull request closed without merging**
