### PR TITLE
3.8.13 bone71 lsm303 1

### PR DESCRIPTION
**Pull request by efargas**
i have tested this patch and works perfectly on 3.8.13 branch.
this patch comes from https://github.com/avterekhov/bb-pwm/

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks @efargas i have it queued up for our 3.8.x tree, after a quick fire test i'll push it out as "bone75"..

https://github.com/RobertCNelson/bb-kernel/commit/2543b5f335e2812369d0de2d21dc92526832b7d5

Regards,

**Comment by efargas** [comment]
see this too #34 jadonk had merged it

**Comment by RobertCNelson** [comment]
@efargas i think i missed that merge...

Can you double check: https://github.com/RobertCNelson/bb-kernel/commits/am33x-v3.8

Regards,

**Comment by RobertCNelson** [comment]
and #34 is merged too: https://github.com/RobertCNelson/bb-kernel/commit/360c9dac24c4590af361b12342398ff5b11349c0

**Comment by efargas** [comment]
Fantastic ;)

**Comment by jadonk** [comment]
Does this additional patch need to be merged or should this pull request be closed?

**Comment by RobertCNelson** [comment]
It got merged in 3.8, need to double check it works on 4.1

**Comment by jadonk** [comment]
Does this need to go to 4.4?

**Pull request closed without merging**
