### PR TITLE
Update bb.org_defconfig

### PR DESCRIPTION
**Pull request by Pillar1989**
suport wl1835 bluetooth

### CODE REVIEW

**Comment by jadonk** [comment]
Why not simply blacklist this module? I'm confused how BlueZ works without this driver. What is the replacement driver?

**Comment by RobertCNelson** [comment]
I need to add the blacklist to the bb-customizstion Debian package, then I'll reenable the modules.

**Comment by jadonk** [comment]
What's the status on this one?

**Comment by RobertCNelson** [comment]
We are currently blacklisting the module via the "bb-wl18xx-firmware" deb package:

https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/jessie/debian/btwilink-blacklist.conf

bluez's been working just fine with ^

Safe to close...

Regards,

**Pull request closed without merging**
