### PR TITLE
BeagleBone DTS : Enable run-time pinmux for HDMI

### PR DESCRIPTION
**Pull request by cdsteinkuehler**
Add cape-universal-hdmi pin info to am335x-bone-common-pinmux.dtsi
Edit hdmi dtsi include files to use new mode= setting to set HDMI
mode at startup, leaving pinmux configurable at runtime.

Signed-off-by: Charles Steinkuehler <charles@steinkuehler.net>

No-audio version works as expected, but HDMI with audio seems to not bring up the display properly.  I think this might have to do with being built as modules instead of being compiled directly into the kernel.

It's easy enough to switch back and forth between the two pinmux methods, just turn all the mode = "hdmi" into status = "disabled" in the nxp-hdmi include files, the pinmux additions can be left in place.

### CODE REVIEW

**Comment by jadonk** [comment]
Can we close this?

**Comment by cdsteinkuehler** [comment]
Closing is OK by me.  This was forever ago, and AFAIK, Robert has moved past this for the 3.14 and 4.x kernels.  Machinekit has not yet moved past the 3.8 xenomai kernel [1], so 3.14 details aren't really an issue for us at this point.

[1] The main plus for 3.14 is better USB support, and USB devices are notorious for causing latency spikes on real-time systems (particularly when hot-plugging).  We're mostly waiting for 4.x PREEMPT_RT and the PRU/remoteproc stuff to sort itself out.

**Comment by cdsteinkuehler** [comment]
Robert: Any reason I shouldn't close this?

**Comment by RobertCNelson** [comment]
This has been merged for awhile.

**Comment by cdsteinkuehler** [comment]
Thanks Robert!

**Pull request closed without merging**
