### PR TITLE
5.10 arm64

### PR DESCRIPTION
**Pull request by ravi-rahul**
Revert the HACKs and fix the issue in DSI driver

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Awesome @ravi-rahul testing right now!

**Comment by ravi-rahul** [comment]
Hi @RobertCNelson 

This PR needs these device tree changes
https://github.com/beagleboard/BeagleBoard-DeviceTrees/pull/64

Please test with device tree changes in above PR

**Comment by RobertCNelson** [comment]
ah so close... DisplayPorts works, but my RPI 7-inch isn't going beyond display init (no logo or console..) merging into staging branch to debug...

**Comment by RobertCNelson** [comment]
On the panel system, @ravi-rahul what's teh best way to see what it tried..

**Comment by ravi-rahul** [comment]
for me it's working, with test build artifacts

**Comment by ravi-rahul** [comment]
dmesg | grep -i RPi
dmesg | grep -i Rasp

**Comment by ravi-rahul** [comment]
sudo apt install libdrm-tests
 modetest -M tidss

**Comment by ravi-rahul** [comment]
can you please share the log of **modetest -M tidss** on your setup

**Comment by RobertCNelson** [comment]
```
debian@BeagleBone:~/$ dmesg | grep -i Rasp
debian@BeagleBone:~/$ sudo beagle-version | grep UBOOT
UBOOT: Booted Device-Tree:[k3-j721e-beagleboneai64.dts]
UBOOT: Loaded Overlay:[BBAI64-DSI-RPi-7inch-panel.kernel]
debian@BeagleBone:~/$ dmesg | grep -i Rasp
```

BBAI64-DSI-RPi-7inch-panel is just a renamed version of yours..

**Comment by RobertCNelson** [comment]
```
debian@BeagleBone:~/$ modetest -M tidss
Encoders:
id      crtc    type    possible crtcs  possible clones
38      0       none    0x00000001      0x00000001
47      46      none    0x00000002      0x00000002

Connectors:
id      encoder status          name            size (mm)       modes   encoders
39      0       disconnected    DP-1            0x0             0       38
  props:
        1 EDID:
                flags: immutable blob
                blobs:

                value:
        2 DPMS:
                flags: enum
                enums: On=0 Standby=1 Suspend=2 Off=3
                value: 0
        5 link-status:
                flags: enum
                enums: Good=0 Bad=1
                value: 0
        6 non-desktop:
                flags: immutable range
                values: 0 1
                value: 0
        4 TILE:
                flags: immutable blob
                blobs:

                value:
48      47      connected       DSI-1           154x86          1       47
  modes:
        index name refresh (Hz) hdisp hss hse htot vdisp vss vse vtot
  #0 800x480 60.00 800 848 880 960 480 483 490 496 28569 flags: nhsync, nvsync; type: preferred, driver
  props:
        1 EDID:
                flags: immutable blob
                blobs:

                value:
        2 DPMS:
                flags: enum
                enums: On=0 Standby=1 Suspend=2 Off=3
                value: 0
        5 link-status:
                flags: enum
                enums: Good=0 Bad=1
                value: 0
        6 non-desktop:
                flags: immutable range
                values: 0 1
                value: 0
        4 TILE:
                flags: immutable blob
                blobs:

                value:

CRTCs:
id      fb      pos     size
37      0       (0,0)   (0x0)
  #0  nan 0 0 0 0 0 0 0 0 0 flags: ; type: 
  props:
        24 VRR_ENABLED:
                flags: range
                values: 0 1
                value: 0
        27 CTM:
                flags: blob
                blobs:

                value:
        28 GAMMA_LUT:
                flags: blob
                blobs:

                value:
        29 GAMMA_LUT_SIZE:
                flags: immutable range
                values: 0 4294967295
                value: 256
46      61      (0,0)   (800x480)
  #0 800x480 60.00 800 848 880 960 480 483 490 496 28569 flags: nhsync, nvsync; type: preferred, driver
  props:
        24 VRR_ENABLED:
                flags: range
                values: 0 1
                value: 0
        27 CTM:
                flags: blob
                blobs:

                value:
        28 GAMMA_LUT:
                flags: blob
                blobs:

                value:
        29 GAMMA_LUT_SIZE:
                flags: immutable range
                values: 0 4294967295
                value: 256

Planes:
id      crtc    fb      CRTC x,y        x,y     gamma size      possible crtcs
31      0       0       0,0             0,0     0               0x00000003
  formats: AR12 AB12 RA12 RG16 BG16 AR15 AB15 AR24 AB24 RA24 BA24 RG24 BG24 AR30 AB30 XR12 XB12 RX12 AR15 AB15 XR24 XB24 RX24 BX24 XR30 XB30 YUYV UYVY NV12
  props:
        8 type:
                flags: immutable enum
                enums: Overlay=0 Primary=1 Cursor=2
                value: 1
        32 zpos:
                flags: range
                values: 0 3
                value: 0
        33 COLOR_ENCODING:
                flags: enum
                enums: ITU-R BT.601 YCbCr=0 ITU-R BT.709 YCbCr=1
                value: 0
        34 COLOR_RANGE:
                flags: enum
                enums: YCbCr limited range=0 YCbCr full range=1
                value: 0
        35 alpha:
                flags: range
                values: 0 65535
                value: 65535
        36 pixel blend mode:
                flags: enum
                enums: Pre-multiplied=0 Coverage=1
                value: 0
40      46      61      0,0             0,0     0               0x00000003
  formats: AR12 AB12 RA12 RG16 BG16 AR15 AB15 AR24 AB24 RA24 BA24 RG24 BG24 AR30 AB30 XR12 XB12 RX12 AR15 AB15 XR24 XB24 RX24 BX24 XR30 XB30 YUYV UYVY NV12
  props:
        8 type:
                flags: immutable enum
                enums: Overlay=0 Primary=1 Cursor=2
                value: 1
        41 zpos:
                flags: range
                values: 0 3
                value: 0
        42 COLOR_ENCODING:
                flags: enum
                enums: ITU-R BT.601 YCbCr=0 ITU-R BT.709 YCbCr=1
                value: 0
        43 COLOR_RANGE:
                flags: enum
                enums: YCbCr limited range=0 YCbCr full range=1
                value: 0
        44 alpha:
                flags: range
                values: 0 65535
                value: 65535
        45 pixel blend mode:
                flags: enum
                enums: Pre-multiplied=0 Coverage=1
                value: 0
49      0       0       0,0             0,0     0               0x00000003
  formats: AR12 AB12 RA12 RG16 BG16 AR15 AB15 AR24 AB24 RA24 BA24 RG24 BG24 AR30 AB30 XR12 XB12 RX12 AR15 AB15 XR24 XB24 RX24 BX24 XR30 XB30 YUYV UYVY NV12
  props:
        8 type:
                flags: immutable enum
                enums: Overlay=0 Primary=1 Cursor=2
                value: 0
        50 zpos:
                flags: range
                values: 0 3
                value: 0
        51 COLOR_ENCODING:
                flags: enum
                enums: ITU-R BT.601 YCbCr=0 ITU-R BT.709 YCbCr=1
                value: 0
        52 COLOR_RANGE:
                flags: enum
                enums: YCbCr limited range=0 YCbCr full range=1
                value: 0
        53 alpha:
                flags: range
                values: 0 65535
                value: 65535
        54 pixel blend mode:
                flags: enum
                enums: Pre-multiplied=0 Coverage=1
                value: 0
55      0       0       0,0             0,0     0               0x00000003
  formats: AR12 AB12 RA12 RG16 BG16 AR15 AB15 AR24 AB24 RA24 BA24 RG24 BG24 AR30 AB30 XR12 XB12 RX12 AR15 AB15 XR24 XB24 RX24 BX24 XR30 XB30 YUYV UYVY NV12
  props:
        8 type:
                flags: immutable enum
                enums: Overlay=0 Primary=1 Cursor=2
                value: 0
        56 zpos:
                flags: range
                values: 0 3
                value: 0
        57 COLOR_ENCODING:
                flags: enum
                enums: ITU-R BT.601 YCbCr=0 ITU-R BT.709 YCbCr=1
                value: 0
        58 COLOR_RANGE:
                flags: enum
                enums: YCbCr limited range=0 YCbCr full range=1
                value: 0
        59 alpha:
                flags: range
                values: 0 65535
                value: 65535
        60 pixel blend mode:
                flags: enum
                enums: Pre-multiplied=0 Coverage=1
                value: 0

Frame buffers:
id      size    pitch
```

**Comment by ravi-rahul** [comment]
dmesg | grep tc35

**Comment by RobertCNelson** [comment]
backlight is on, but i don't have any console prompt..

**Comment by ravi-rahul** [comment]
kmstest

**Comment by ravi-rahul** [comment]
can you run this command

**Comment by ravi-rahul** [comment]
can you please try below command and see if you get anything on the panel
modetest -M tidss -s 48@46:800x480

**Comment by RobertCNelson** [comment]
just stays blank..

```
debian@BeagleBone:~/$ modetest -M tidss -s 48@46:800x480
setting mode 800x480-60.00Hz on connectors 48, crtc 46
```

**Comment by ravi-rahul** [comment]
cat /proc/device-tree/bus@100000/dsi@48000000/compatible

**Comment by RobertCNelson** [comment]
```
debian@BeagleBone:~/$ cat /proc/device-tree/bus@100000/dsi@48000000/compatible
ti,j721e-dsi
```

**Comment by ravi-rahul** [comment]
root@BeagleBone:/home/debian# beagle-version | grep -i uboot
UBOOT: Booted Device-Tree:[k3-j721e-beagleboneai64.dts]
UBOOT: Loaded Overlay:[BBAI64-DSI-RPi-7inch-panel.kernel]
root@BeagleBone:/home/debian# uname -r
5.10.145-ti-arm64-staging-r72.1
root@BeagleBone:/home/debian# md5sum /boot/firmware/Image
46cd0c1979cf543df7ac2781a733db66  /boot/firmware/Image
root@BeagleBone:/home/debian# md5sum /boot/firmware/overlays/BBAI64-DSI-RPi-7inch-panel.dtbo
91b53360da6228e45fbcc7fc81b8e67b  /boot/firmware/overlays/BBAI64-DSI-RPi-7inch-panel.dtbo
root@BeagleBone:/home/debian# md5sum /boot/firmware/k3-j721e-beagleboneai64.dtb
532fbe0c23b1cc2568671ca7879b0a78  /boot/firmware/k3-j721e-beagleboneai64.dtb
root@BeagleBone:/home/debian#

**Comment by RobertCNelson** [comment]
```
debian@BeagleBone:~/$ uname -r
5.10.145-ti-arm64-staging-r72.1
debian@BeagleBone:~/$ md5sum /boot/firmware/*
94e1c0a01c618dcea561041b8d8c167f  /boot/firmware/ID.txt
46cd0c1979cf543df7ac2781a733db66  /boot/firmware/Image
md5sum: /boot/firmware/extlinux: Is a directory
52244c7636ad3e9e00438a3b14993707  /boot/firmware/initrd.img
532fbe0c23b1cc2568671ca7879b0a78  /boot/firmware/k3-j721e-beagleboneai64.dtb

91b53360da6228e45fbcc7fc81b8e67b  /boot/firmware/overlays/BBAI64-DSI-RPi-7inch-panel.dtbo
```

grabing another card.. (with xfce installed).. this was just a test console image, that had always shown a prompt..

Regards,

**Comment by RobertCNelson** [comment]
full

**Comment by RobertCNelson** [comment]
usb on the back is powered, but this is how i have it setup, and how the screen looked prior to the patches..

**Comment by ravi-rahul** [comment]
setup looks correct, not sure what is the issue

**Comment by RobertCNelson** [comment]
so... with a fresh xfce image... 
PXL_20221115_171634120

i don't know why basic console broke..

**Comment by ravi-rahul** [comment]
got it

**Comment by RobertCNelson** [comment]
i'll push it out.. not sure why console is broken, but x works..

**Comment by ravi-rahul** [comment]
Thanks !

**Pull request closed without merging**
