### PR TITLE
Backport of pcm5122 driver

### PR DESCRIPTION
**Pull request by hmbedded**
This is my first time asking for something to be added to the beaglebone kernel. I assumed that as it's on github a PR is the correct approach. If not or if I need to copy to a mailing list I'd be grateful if someone could point me in the right direction.

This is a backport of the driver for the pcm5122 DAC from the upstream mainline kernel. This is for a new cape being developed by IQaudIO (http://iqaudio.com). It's essentially a re-spin of the Pi-DAC+ product. I intend to follow up with the board driver at a later date.

Best regards,
Howard Mitchell

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks!  I'll queue this up in my staging branch. so users can test it out. Since i'm heading to ELC on sunday, i'm not planing to push any builds out, so it'll get a good week of testing..

**Comment by hmbedded** [comment]
Just wanted to let you know that I've found a couple of bugs in this driver since I made the PR so you may want to hold off fully merging for now. I've submitted a couple of patches upstream and they're currently going through the review process. I'll update this PR once they make it to the mainline kernel.

**Comment by RobertCNelson** [comment]
No worries, the 3.8.x branch is in mostly maintenance mode, which means we are really only pulling in features/patches that you cape developers need. ;)  So just take your time, but if it goes out with an issue, we can quickly rebuild and push out again quickly too...

**Comment by jadonk** [comment]
Any updates on the fixing these bugs?

**Comment by RobertCNelson** [comment]
@hmbedded how about v4.1.x? less to backport...

kernel: https://github.com/beagleboard/linux/tree/4.1
cape: https://github.com/RobertCNelson/bb.org-overlays

**Comment by hmbedded** [comment]
@RobertCNelson In fact I see the bug fixes I submitted upstream have made it to the 4.1 tree so there's nothing at all to backport. Also the cape development has been put on a back burner due to other priorities so, given that beaglebone is moving to 4.1 tree, I think it's better that we target this for future work rather than backporting to 3.8. I'm therefore closing this PR.

**Pull request closed without merging**
