### PR TITLE
Fix remoteproc to work with the PRU GNU Binutils port

### PR DESCRIPTION
**Pull request by dinuxbg**
PRU IRAM addresses need to be masked before being handled to
remoteproc. This is due to PRU Binutils' lack of separate address
spaces for IRAM and DRAM.

Signed-off-by: Dimitar Dimitrov <dinuxbg@gmail.com>

### CODE REVIEW

**Comment by dinuxbg** [comment]
I tested this patch on top of Linux beaglebone 4.9.13-ti-r24, using https://github.com/dinuxbg/pru-gcc-examples/tree/master/blinking-led/pru .

**Comment by dlech** [comment]
Will this break PRU firmware compiled with the TI compiler?

**Comment by RobertCNelson** [comment]
it hasn't in the past (v4.1.x-ti and v4.4.x-ti). ;)

**Comment by dinuxbg** [comment]
Patch is safe - it does not break TI CGT.

**Comment by RobertCNelson** [comment]
@dinuxbg sorry for the delay, pushed out as part of r25

**Pull request closed without merging**
