### PR TITLE
Bb blue api

### PR DESCRIPTION
**Pull request by kiran4399**

### CODE REVIEW

**Comment by RobertCNelson** [comment]
I'm going to merge this BUT leave the two config's disabled:

```
  CC [M]  drivers/iio/imu/inv_mpu9150/inv_mpu_core.o
In file included from drivers/iio/imu/inv_mpu9150/inv_mpu_core.c:31:0:
drivers/iio/imu/inv_mpu9150/inv_mpu_iio.h:21:23: fatal error: linux/mpu.h: No such file or directory
compilation terminated.
scripts/Makefile.build:258: recipe for target 'drivers/iio/imu/inv_mpu9150/inv_mpu_core.o' failed
make[4]: *** [drivers/iio/imu/inv_mpu9150/inv_mpu_core.o] Error 1
scripts/Makefile.build:403: recipe for target 'drivers/iio/imu/inv_mpu9150' failed
make[3]: *** [drivers/iio/imu/inv_mpu9150] Error 2
scripts/Makefile.build:403: recipe for target 'drivers/iio/imu' failed
make[2]: *** [drivers/iio/imu] Error 2
scripts/Makefile.build:403: recipe for target 'drivers/iio' failed
make[1]: *** [drivers/iio] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:946: recipe for target 'drivers' failed
make: *** [drivers] Error 2
make: *** Waiting for unfinished jobs....


drivers/iio/pressure/bmp180.c:54:26: fatal error: linux/bmp180.h: No such file or directory
compilation terminated.
  CC [M]  drivers/iio/light/tsl4531.o
scripts/Makefile.build:264: recipe for target 'drivers/iio/pressure/bmp180.o' failed
make[3]: *** [drivers/iio/pressure/bmp180.o] Error 1
  CC      drivers/irqchip/irqchip.o
scripts/Makefile.build:403: recipe for target 'drivers/iio/pressure' failed
make[2]: *** [drivers/iio/pressure] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by RobertCNelson** [comment]
Wait, mpu9150 support was added to mainline:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/drivers/iio/imu

**Comment by RobertCNelson** [comment]
@kiran4399 can you please re-test:

https://github.com/beagleboard/linux/tree/4.4.11-ti-rt-r29

I've back ported mpu9150 support from the mainline.

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=fbced0e9465152d628ece5fd0d11de4e7a1f5ce5

can you check and see if it works for you, if not i'll dump that large backport and try re-patch these 5 commits..

Regards,

**Comment by jadonk** [comment]
@kiran4399 any updates?

**Comment by kiran4399** [comment]
I'm sorry.. Did'nt see the message.
@jadonk @RobertCNelson 

I checked it. I got some more sysfs entries on the mpu-6500 in /sys/bus/iio/devices/iio:device0..
but the magnetometer has no entries :-(

**Comment by RobertCNelson** [comment]
Closing, please re-submit, when cleaned up.

Currently this triggers the auto-builder:

http://rcn-ee.online:8080/job/beagleboard_kernel_builder/view/change-requests/job/PR-91/

Regards,

**Pull request closed without merging**
